name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Publish to Surge
        run: |
          npm install -g surge
          surge ./build https://docs.solayf.com --token ${{ secrets.SURGE_TOKEN }}
